//! A tiny deterministic PRNG (SplitMix64).
//!
//! Determinism underpins this crate's simulation support — scheduling and
//! simulated entropy in the executor, plus `Backend`-level fault injection and
//! the crash nemesis built on top — and the bit-mixing constants below must
//! match exactly for replays to stay byte-for-byte stable. A single
//! zero-dependency generator lives here so those callers share one source of
//! truth instead of each re-implementing it.

/// A seedable [SplitMix64](https://prng.di.unimi.it/splitmix64.c) generator.
/// Zero-dependency and fully deterministic: the same seed yields the same
/// sequence, so simulation runs replay identically.
#[derive(Clone)]
pub struct Rng(u64);

impl Rng {
    /// Creates a generator seeded with `seed`.
    pub fn new(seed: u64) -> Self {
        Rng(seed)
    }

    /// Returns the next 64-bit value and advances the state.
    pub fn next_u64(&mut self) -> u64 {
        self.0 = self.0.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = self.0;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    /// Returns a value in `0..n`, or `0` when `n == 0`.
    pub fn below(&mut self, n: u64) -> u64 {
        if n == 0 {
            0
        } else {
            self.next_u64() % n
        }
    }

    /// Fills `buf` with generated bytes.
    pub fn fill(&mut self, buf: &mut [u8]) {
        for chunk in buf.chunks_mut(8) {
            let v = self.next_u64().to_le_bytes();
            for (b, vb) in chunk.iter_mut().zip(v) {
                *b = vb;
            }
        }
    }
}
