// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TransactionLog {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration = "transaction_log::Status", tag = "2")]
    pub status: i32,
    #[prost(message, repeated, tag = "3")]
    pub writes: ::prost::alloc::vec::Vec<CollectionWrites>,
}
/// Nested message and enum types in `TransactionLog`.
pub mod transaction_log {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum Status {
        Default = 0,
        Committed = 1,
        Aborted = 2,
        Pending = 3,
    }
    impl Status {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Default => "DEFAULT",
                Self::Committed => "COMMITTED",
                Self::Aborted => "ABORTED",
                Self::Pending => "PENDING",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DEFAULT" => Some(Self::Default),
                "COMMITTED" => Some(Self::Committed),
                "ABORTED" => Some(Self::Aborted),
                "PENDING" => Some(Self::Pending),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectionWrites {
    #[prost(string, tag = "1")]
    pub prefix: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub writes: ::prost::alloc::vec::Vec<Write>,
    #[prost(message, optional, tag = "3")]
    pub locks: ::core::option::Option<CollectionLocks>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Write {
    #[prost(string, tag = "1")]
    pub suffix: ::prost::alloc::string::String,
    /// The ID of the last transaction writing to this key.
    #[prost(bytes = "vec", tag = "3")]
    pub prev_tid: ::prost::alloc::vec::Vec<u8>,
    #[prost(oneof = "write::ValDelete", tags = "2, 4")]
    pub val_delete: ::core::option::Option<write::ValDelete>,
}
/// Nested message and enum types in `Write`.
pub mod write {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum ValDelete {
        #[prost(bytes, tag = "2")]
        Value(::prost::alloc::vec::Vec<u8>),
        #[prost(bool, tag = "4")]
        Deleted(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectionLocks {
    #[prost(enumeration = "lock::LockType", tag = "2")]
    pub collection_lock: i32,
    #[prost(message, repeated, tag = "3")]
    pub locks: ::prost::alloc::vec::Vec<Lock>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Lock {
    #[prost(string, tag = "1")]
    pub suffix: ::prost::alloc::string::String,
    #[prost(enumeration = "lock::LockType", tag = "2")]
    pub lock_type: i32,
}
/// Nested message and enum types in `Lock`.
pub mod lock {
    #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
    #[repr(i32)]
    pub enum LockType {
        Unknown = 0,
        None = 1,
        Read = 2,
        Write = 3,
        Create = 4,
    }
    impl LockType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Unknown => "UNKNOWN",
                Self::None => "NONE",
                Self::Read => "READ",
                Self::Write => "WRITE",
                Self::Create => "CREATE",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNKNOWN" => Some(Self::Unknown),
                "NONE" => Some(Self::None),
                "READ" => Some(Self::Read),
                "WRITE" => Some(Self::Write),
                "CREATE" => Some(Self::Create),
                _ => None,
            }
        }
    }
}
/// A shard object: the coordination directory (lock table, MVCC current-writer
/// index, and key directory) for the keys that map to it. See ADR-017.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Shard {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<ShardEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShardEntry {
    /// Raw user key bytes; also the entry's sort key.
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    /// Lock currently held on the key.
    #[prost(enumeration = "lock::LockType", tag = "2")]
    pub lock_type: i32,
    /// Transactions holding the lock (more than one only for read locks).
    #[prost(bytes = "vec", repeated, tag = "3")]
    pub locked_by: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Transaction object holding the committed value (the MVCC pointer); empty
    /// if the key has no committed value yet.
    #[prost(bytes = "vec", tag = "4")]
    pub current_writer: ::prost::alloc::vec::Vec<u8>,
    /// Tombstone flag.
    #[prost(bool, tag = "5")]
    pub deleted: bool,
}
/// A B-link tree node: the unit of the dynamic, range-partitioned coordination
/// directory (ADR-031). It is either a leaf (the per-key coordination entries of
/// ADR-017 for a contiguous key range) or an index (separator keys mapping
/// ranges to child nodes). The high-key and right-sibling make tree descent
/// self-correcting across concurrent splits.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Node {
    /// Exclusive upper bound of the key range this node owns. Empty means
    /// +infinity: the rightmost node at its level.
    #[prost(bytes = "vec", tag = "1")]
    pub high_key: ::prost::alloc::vec::Vec<u8>,
    /// Identity token of the right-sibling node at the same level. Empty means
    /// none: the rightmost node at its level.
    #[prost(string, tag = "2")]
    pub right_sibling: ::prost::alloc::string::String,
    #[prost(oneof = "node::Body", tags = "3, 4")]
    pub body: ::core::option::Option<node::Body>,
}
/// Nested message and enum types in `Node`.
pub mod node {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        /// A leaf node: the per-key coordination entries for its range.
        #[prost(message, tag = "3")]
        Leaf(super::Shard),
        /// An index node: separator keys mapping ranges to child nodes.
        #[prost(message, tag = "4")]
        Index(super::IndexNode),
    }
}
/// An index node body: an ordered list of separator entries. The child owning a
/// key is the last entry whose separator_key is <= the key.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndexNode {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<IndexEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IndexEntry {
    /// Inclusive lower bound of the child's key range; sorted so the encoding is
    /// canonical.
    #[prost(bytes = "vec", tag = "1")]
    pub separator_key: ::prost::alloc::vec::Vec<u8>,
    /// Identity token of the child node.
    #[prost(string, tag = "2")]
    pub child: ::prost::alloc::string::String,
}
/// Database-level metadata, written once at `{name}/glassdb` when a database is
/// first opened. Its presence marks the database as initialized; `version` gates
/// on-disk format compatibility. A message (not a bare string) so new metadata
/// fields can be added without breaking existing databases.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DatabaseMetadata {
    /// On-disk format version identifier (e.g. "v2").
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
}
/// The collection root object `{prefix}/_i` (ADR-031). It *is* the B-link tree's
/// root node - a leaf while the collection is small, an index once it grows - and
/// also carries the collection metadata: the subcollection directory and the
/// membership lock that serializes create/delete against listing. Supersedes
/// ADR-018's fixed-shard_count root.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CollectionRoot {
    /// The B-link tree root node. Its high-key is +infinity and its right-sibling
    /// is empty (the root has no siblings).
    #[prost(message, optional, tag = "1")]
    pub node: ::core::option::Option<Node>,
    /// Child collection names (raw bytes), the subcollection directory; sorted so
    /// the encoding is canonical.
    #[prost(bytes = "vec", repeated, tag = "2")]
    pub subcollections: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    /// Membership lock serializing create/delete (write) against listing (read).
    #[prost(enumeration = "lock::LockType", tag = "3")]
    pub membership_lock: i32,
    /// Transactions holding the membership lock (more than one only for read
    /// locks); sorted so the encoding is canonical.
    #[prost(bytes = "vec", repeated, tag = "4")]
    pub membership_locked_by: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
}
