[package]
name = "glassdb-data"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Low level data types for GlassDB (internal crate)."

[lints]
workspace = true

[dependencies]
glassdb-concurr = { version = "0.2.1", path = "../glassdb-concurr" }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
